// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhooswniklnmunmvlaoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob29zd25pa2xubXVubXZsYW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzkxNTgsImV4cCI6MjA2OTkxNTE1OH0.tym9GKflW-9V3UK1yfyujxxKApE6J3daaqCvsQ3QMi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});